# config/services.yaml

parameters:
    photos_directory: '%kernel.project_dir%/public/images/tours'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\Admin\UtilisateurController:
        arguments:
            $photosDirectory: '%photos_directory%'

    App\Controller\Admin\TourController:
        arguments:
            $photosDirectory: '%photos_directory%'
